### ISSUE TITLE
webpage build GHA doesn't run on automated commits

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_metrics#29]
This commit from the scheduled GHA didn't kick off the webpage building GHA.
https://github.com/ioos/ioos_metrics/commit/adc249a77174c89a2eb1e843304d350163185dc9

I had to run the webpage build manually:
* https://github.com/ioos/ioos_metrics/actions/runs/5523809786

I'm befuddled as I thought the action was ran on any new commits to `main` with:
```yaml
on:
  workflow_dispatch:
  push:
    branches:
      - main
```

see https://github.com/ioos/ioos_metrics/blob/main/.github/workflows/website_create_and_deploy.yml
